name: 🌐 Deploy Frontend to GCS

on:
  push:
    branches:
      - main
      - produccion

env:
  BUCKET_NAME: prospect2-chat-web
  FRONTEND_DIR: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 📤 Upload Frontend to Google Cloud Storage
    environment: deploy

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 🧰 Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: 🚀 Upload files to GCS with no-cache headers
        run: |
          gsutil -m -h "Cache-Control:no-cache,max-age=0" cp -r $FRONTEND_DIR/* gs://$BUCKET_NAME
